#!/bin/bash
# GA Configuration - generated by ga_setup.sh
# Modify via: ./ga/scripts/ga_setup.sh --population=X ...

# Population settings
POPULATION=5
GENERATIONS=2
OFFSPRING=3

# Genetic operator rates
CROSSOVER_RATE=0.8
MUTATION_RATE=0.2
