#!/bin/bash
# GA Configuration - generated by ga_setup.sh
# Modify via: ./ga/scripts/ga_setup.sh --population=X ...

# Population settings (optimized for expensive LLM-based fitness evaluations)
POPULATION=8
GENERATIONS=5
OFFSPRING=6

# Genetic operator rates
CROSSOVER_RATE=0.7
MUTATION_RATE=0.3
