#!/bin/bash
# GA Configuration - generated by ga_setup.sh
# Modify via: ./ga/scripts/ga_setup.sh --population=X ...

# Population settings (optimized for LLM-based genetic operators)
POPULATION=8
GENERATIONS=5
OFFSPRING=6

# Genetic operator rates (balanced for LLM-guided evolution)
CROSSOVER_RATE=0.5
MUTATION_RATE=0.5
