#!/bin/bash
# GA Setup - Configure GA parameters before running optimization
# Usage: ./ga/scripts/ga_setup.sh [options]
#
# Options:
#   --population=N       Population size (default: 10)
#   --generations=N      Number of generations (default: 50)
#   --offspring=N        Offspring per generation (default: 8)
#   --crossover-rate=N   Probability of crossover vs mutation (default: 0.5)
#   --mutation-rate=N    Mutation probability (default: 0.5)
#   --reset              Clear existing state and start fresh
#
# Example:
#   ./ga/scripts/ga_setup.sh --population=10 --generations=50 --reset

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GA_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$SCRIPT_DIR/ga_config.sh"

# Defaults (optimized for long overnight LLM-based runs)
# Research: mutation more effective in small populations; LLMs are intelligent operators
# See: https://arxiv.org/html/2403.11446v1, https://pmc.ncbi.nlm.nih.gov/articles/PMC4137700/
POPULATION=10      # Moderate population for diversity
GENERATIONS=50     # High for overnight runs (50 gens * ~10min/gen ≈ 8 hours)
OFFSPRING=8        # 80% replacement rate - good exploration
CROSSOVER_RATE=0.5 # Balanced: crossover combines winning strategies
MUTATION_RATE=0.5  # Balanced: mutation explores new directions
RESET=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --population=*)
            POPULATION="${arg#*=}"
            ;;
        --generations=*)
            GENERATIONS="${arg#*=}"
            ;;
        --offspring=*)
            OFFSPRING="${arg#*=}"
            ;;
        --crossover-rate=*)
            CROSSOVER_RATE="${arg#*=}"
            ;;
        --mutation-rate=*)
            MUTATION_RATE="${arg#*=}"
            ;;
        --reset)
            RESET=true
            ;;
        --help|-h)
            head -15 "$0" | tail -n +2 | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Use --help for usage"
            exit 1
            ;;
    esac
done

# Write config file
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# GA Configuration - generated by ga_setup.sh
# Modify via: ./ga/scripts/ga_setup.sh --population=X ...

# Population settings
POPULATION=$POPULATION
GENERATIONS=$GENERATIONS
OFFSPRING=$OFFSPRING

# Genetic operator rates
CROSSOVER_RATE=$CROSSOVER_RATE
MUTATION_RATE=$MUTATION_RATE
EOF

echo "[CONFIG] Written to $CONFIG_FILE:"
echo "  POPULATION=$POPULATION"
echo "  GENERATIONS=$GENERATIONS"
echo "  OFFSPRING=$OFFSPRING"
echo "  CROSSOVER_RATE=$CROSSOVER_RATE"
echo "  MUTATION_RATE=$MUTATION_RATE"

# Reset if requested
if [ "$RESET" = true ]; then
    echo "[RESET] Clearing existing state..."
    rm -rf "$GA_DIR/candidates/CAND_"* \
           "$GA_DIR/candidates/state.txt" \
           "$GA_DIR/candidates/scores.txt" \
           "$GA_DIR/candidates/eval_cache.txt" \
           "$GA_DIR/optimization_progress.txt" \
           "$GA_DIR/best" 2>/dev/null || true
    echo "[RESET] Ready for fresh start"
fi
