#!/bin/bash
# SA Configuration - generated by sa_setup.sh
# Modify via: ./sa/scripts/sa_setup.sh --initial-temp=X ...

# Temperature schedule
INITIAL_TEMP=5000
FINAL_TEMP=10
COOLING_RATE=0.95

# Iteration control
ITERATIONS_PER_TEMP=1
MAX_ITERATIONS=500
