#!/bin/bash
# SA Setup - Configure SA parameters before running optimization
# Usage: ./sa/scripts/sa_setup.sh [options]
#
# Options:
#   --initial-temp=N     Starting temperature (default: 5000)
#   --final-temp=N       Stopping temperature (default: 10)
#   --cooling-rate=N     Multiplicative cooling factor (default: 0.95)
#   --iterations-per-temp=N  Steps per temperature level (default: 1)
#   --max-iterations=N   Hard limit on iterations (default: 500)
#   --reset              Clear existing state and start fresh
#
# Example:
#   ./sa/scripts/sa_setup.sh --initial-temp=1000 --cooling-rate=0.9 --reset

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SA_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$SCRIPT_DIR/sa_config.sh"

# Defaults
INITIAL_TEMP=5000
FINAL_TEMP=10
COOLING_RATE=0.95
ITERATIONS_PER_TEMP=1
MAX_ITERATIONS=500
RESET=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --initial-temp=*)
            INITIAL_TEMP="${arg#*=}"
            ;;
        --final-temp=*)
            FINAL_TEMP="${arg#*=}"
            ;;
        --cooling-rate=*)
            COOLING_RATE="${arg#*=}"
            ;;
        --iterations-per-temp=*)
            ITERATIONS_PER_TEMP="${arg#*=}"
            ;;
        --max-iterations=*)
            MAX_ITERATIONS="${arg#*=}"
            ;;
        --reset)
            RESET=true
            ;;
        --help|-h)
            head -20 "$0" | tail -n +2 | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Use --help for usage"
            exit 1
            ;;
    esac
done

# Write config file
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# SA Configuration - generated by sa_setup.sh
# Modify via: ./sa/scripts/sa_setup.sh --initial-temp=X ...

# Temperature schedule
INITIAL_TEMP=$INITIAL_TEMP
FINAL_TEMP=$FINAL_TEMP
COOLING_RATE=$COOLING_RATE

# Iteration control
ITERATIONS_PER_TEMP=$ITERATIONS_PER_TEMP
MAX_ITERATIONS=$MAX_ITERATIONS
EOF

echo "[CONFIG] Written to $CONFIG_FILE:"
echo "  INITIAL_TEMP=$INITIAL_TEMP"
echo "  FINAL_TEMP=$FINAL_TEMP"
echo "  COOLING_RATE=$COOLING_RATE"
echo "  ITERATIONS_PER_TEMP=$ITERATIONS_PER_TEMP"
echo "  MAX_ITERATIONS=$MAX_ITERATIONS"

# Reset if requested
if [ "$RESET" = true ]; then
    echo "[RESET] Clearing existing state..."
    rm -rf "$SA_DIR/candidates/CAND_"* \
           "$SA_DIR/candidates/state.txt" \
           "$SA_DIR/candidates/history.txt" \
           "$SA_DIR/candidates/eval_cache.txt" \
           "$SA_DIR/candidates/scores.txt" 2>/dev/null || true
    echo "[RESET] Ready for fresh start"
fi
