#!/bin/bash
# LNS Setup - Configure LNS parameters before running optimization
# Usage: ./lns/scripts/lns_setup.sh [options]
#
# Options:
#   --max-iterations=N   Hard limit on iterations (default: 100)
#   --reset              Clear existing state and start fresh
#
# Example:
#   ./lns/scripts/lns_setup.sh --max-iterations=50 --reset

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LNS_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$SCRIPT_DIR/lns_config.sh"

# Defaults
MAX_ITERATIONS=100
RESET=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --max-iterations=*)
            MAX_ITERATIONS="${arg#*=}"
            ;;
        --reset)
            RESET=true
            ;;
        --help|-h)
            head -12 "$0" | tail -n +2 | sed 's/^# //' | sed 's/^#//'
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Use --help for usage"
            exit 1
            ;;
    esac
done

# Write config file
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# LNS Configuration - generated by lns_setup.sh
# Modify via: ./lns/scripts/lns_setup.sh --max-iterations=X ...

MAX_ITERATIONS=$MAX_ITERATIONS
EOF

echo "[CONFIG] Written to $CONFIG_FILE:"
echo "  MAX_ITERATIONS=$MAX_ITERATIONS"

# Reset if requested
if [ "$RESET" = true ]; then
    echo "[RESET] Clearing existing state..."
    rm -rf "$LNS_DIR/candidates/CAND_"* \
           "$LNS_DIR/candidates/state.txt" \
           "$LNS_DIR/candidates/eval_cache.txt" 2>/dev/null || true
    # Note: operators.txt is NOT reset - it contains learned knowledge
    echo "[RESET] Candidates and state cleared (operators.txt preserved)"
    echo "[RESET] Ready for fresh start"
fi
